# This file is part of the BenGorCookies library.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sudo: false

language: node_js

node_js:
  - 6
  - 7
  - 8

install:
    - npm install

script:
    - npm test -- --coverage
    - node_modules/.bin/eslint -c .eslintrc.js src/js/ test/
    - node_modules/.bin/stylelint -c .stylelintrc.js src/scss/**/*.scss --syntax scss
    - node_modules/.bin/prettier 'src/js/**/*.js' 'test/js/**/*.js' --list-different --single-quote --no-bracket-spacing --trailing-comma all --print-width 120

cache:
    directories:
        - node_modules
